# cloudbuild.yaml
steps:
  # Etapa 1: Instalar as dependências do projeto
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    id: 'npm-install'

  # Etapa 2: Executar o build para gerar o script em dist/
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    id: 'npm-build'
    waitFor:
      - 'npm-install'

  # Etapa 3: Copiar o script para a pasta da versão (tag) no GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'cp'
      - 'dist/recorder.min.js'
      - 'gs://cdn-voidr-global/voidr-collector/default/${TAG_NAME}/recorder.min.js'
    id: 'gcs-upload-versioned'
    waitFor:
      - 'npm-build'

  # Etapa 4: Copiar o script para a pasta "latest" no GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'cp'
      - 'dist/recorder.min.js'
      - 'gs://cdn-voidr-global/voidr-collector/default/latest/recorder.min.js'
    id: 'gcs-upload-latest'
    waitFor:
      - 'npm-build'

  # Etapa 5: Invalidar o cache do Cloud CDN para os arquivos atualizados
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'url-maps'
      - 'invalidate-cdn-cache'
      - 'cdn-load-balancer'
      - '--path=/voidr-collector/*'
      - '--async'
    id: 'cdn-invalidate-cache'
    waitFor:
      - 'gcs-upload-latest'

  # Etapa 6: Limpar o cache do Cloudflare
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Acessa o token da API do Secret Manager
        API_TOKEN=mYJjUYJIt_3_RWnlvqiF_EioOWlUdMQSpGAF_Plg

        # Envia a requisição para a API do Cloudflare
        curl -X POST "https://api.cloudflare.com/client/v4/zones/40807c6c48cb5d8a1e29bfbca48a519e/purge_cache" \
          -H "Authorization: Bearer $$API_TOKEN" \
          -H "Content-Type: application/json" \
          --data '{"prefixes":["cdn.voidr.co/voidr-collector"]}'
    id: 'cloudflare-purge-cache'
    waitFor:
      - 'gcdn-invalidate-cache'
