/*
  Environment variables for the Voidr extension.

  This file is COMMITTED and must always point to PRODUCTION — any shipped
  build loads it as-is, so localhost values here would break auth/collector/
  evidence/cookies for real users.

  Local development: do NOT edit this file. Create `config/env.local.js`
  (gitignored — copy `config/env.local.example.js`) with your overrides; it is
  loaded AFTER this file and merges on top of these values.

  Note: Do NOT commit secrets in either file.
*/

(function initializeVoidrEnv() {
  var env = {
    ENVIRONMENT: 'production',
    VOIDR_API_BASE_URL: 'https://api.voidr.co/v1',
    VOIDR_PLATFORM_URL: 'https://platform.voidr.co',
    VOIDR_COLLECTOR_URL: 'https://collector.voidr.co',
  };

  if (typeof globalThis !== 'undefined') {
    globalThis.__VOIDR_ENV__ = env;
  } else if (typeof window !== 'undefined') {
    window.__VOIDR_ENV__ = env;
  } else if (typeof self !== 'undefined') {
    self.__VOIDR_ENV__ = env;
  }
})();
