/*
  Environment variables for the Voidr extension.

  This file is COMMITTED and must always point to PRODUCTION — any shipped
  build loads it as-is, so localhost values here would break auth/collector/
  evidence/cookies for real users.

  Local development: do NOT edit this file. Create `config/env.local.js`
  (gitignored — copy `config/env.local.example.js`) with your overrides; it is
  loaded AFTER this file and merges on top of these values.

  Note: Do NOT commit secrets in either file.
*/

(function initializeVoidrEnv() {
  var env = {
    ENVIRONMENT: 'production',
    VOIDR_API_BASE_URL: 'https://api.voidr.co/v1',
    VOIDR_PLATFORM_URL: 'https://platform.voidr.co',
    VOIDR_COLLECTOR_URL: 'https://collector.voidr.co',

    // Staging
    // VOIDR_API_BASE_URL: 'https://api-staging.voidr.co/v1',
    // VOIDR_PLATFORM_URL: 'https://staging.voidr.co',
    // VOIDR_COLLECTOR_URL: 'https://collector-staging.voidr.co',

    // Local (dev)
    // VOIDR_API_BASE_URL: 'http://localhost:3000/v1',
    // VOIDR_PLATFORM_URL: 'http://localhost:3030',
    // VOIDR_COLLECTOR_URL: 'http://localhost:3333',

    // ---- Auth0 (opcional) --------------------------------------------------
    // Deixe comentado para usar o default de produção (tenant bounties4).
    // Só preencha se o ambiente usar um tenant/app Auth0 diferente.
    // VOIDR_AUTH0_DOMAIN: 'bounties4.us.auth0.com',
    // VOIDR_AUTH0_CLIENT_ID: 'c4eLr6uaq98KB2dCKNkmP9bz6sS3gJfS',
    // VOIDR_AUTH0_AUDIENCE: 'https://service.bounties4.com/',
  };

  if (typeof globalThis !== 'undefined') {
    globalThis.__VOIDR_ENV__ = env;
  } else if (typeof window !== 'undefined') {
    window.__VOIDR_ENV__ = env;
  } else if (typeof self !== 'undefined') {
    self.__VOIDR_ENV__ = env;
  }
})();
